/*
 * Ledger Transactions API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.apache.fineract.infrastructure.odoo.port;

import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.fineract.infrastructure.odoo.OdooApisApi;
import org.apache.fineract.infrastructure.odoo.invoker.ApiCallback;
import org.apache.fineract.infrastructure.odoo.invoker.ApiClient;
import org.apache.fineract.infrastructure.odoo.invoker.ApiException;
import org.apache.fineract.infrastructure.odoo.invoker.ApiResponse;
import org.apache.fineract.infrastructure.odoo.invoker.Configuration;
import org.apache.fineract.infrastructure.odoo.invoker.Pair;
import org.apache.fineract.infrastructure.odoo.model.LedgerAccount;
import org.apache.fineract.infrastructure.odoo.model.SuccessResponse;
import org.apache.fineract.infrastructure.odoo.model.TransactionRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

@Service
public class OdooApisAdapter implements OdooApisPort {

    @Autowired
    private OdooApisApi odooApisApi;


    @Override
    public SuccessResponse odooPostLedger(TransactionRequest transactionRequest) throws ApiException {
        return odooApisApi.odooPostLedger1(transactionRequest);
    }

    @Override
    public SuccessResponse odooPutLedger(TransactionRequest transactionRequest) throws ApiException {
        return odooApisApi.odooPutLedger1(transactionRequest);
    }

    @Override
    public List<LedgerAccount> odooGlAccounts() throws ApiException {
        return odooApisApi.odooGlAccounts1();
    }

    @Override
    public SuccessResponse odooPostGlAccount(LedgerAccount ledgerAccount) throws ApiException {
        return odooApisApi.odooPostGlAccounts1(ledgerAccount);
    }

}
